smartApp/smartApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include 
from student import views
urlpatterns = [
    path('',views.landingPage,name = "landingPage"),
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('subadmin/',include('subadmin.urls')),
]

smartApp/student/urls.py
from django.contrib import admin
from django.urls import path
from student import views
app_name = 'student'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('addview/',views.addView, name = 'addview'),
    path('showattendance/',views.showAttendance, name = 'showattendance'),
    

    
]

smartApp/subadmin/urls.py
from django.contrib import admin
from django.urls import path
from subadmin import views
app_name = 'subadmin'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('login/',views.admin_login, name = 'login'),
    path('logout/',views.admin_logout, name = 'logout'),
    path('addclass/',views.createClass,name = 'addclass'),
    path('showclass/',views.showClass,name = 'showclass'),
    path('editclass/<int:id>',views.editClass),
    path('updateclass/',views.updateClass, name = 'updateclass'),
    path('deleteclass/<int:id>',views.deleteClass),

    
]

smartApp/teacher/urls.py
from django.contrib import admin
from django.urls import path
from teacher import views
app_name = 'teacher'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('getstudentbyyear/<str:subject>',views.getStudentByYear,name = 'getstudentbyyear'),
    path('showStudentByTeacher',views.showStudentByTeacher ,name = 'showStudentByTeacher'),
    path('insertstdwicourse',views.insertStdWiCourse ,name = 'insertstdwicourse'),
    path('takeattendance/',views.takeAttendance,name = 'takeattendance'),
    path('addattendance/',views.addAttendance, name = 'addattendance'),
    path('attendance/',views.Attendance, name = 'attendance'),
    path('showattendance/',views.showAttendance,name = 'showattendance'),
    path('viewattendance/',views.viewAttendance,name = 'viewattendance')
    

    
]

smartApp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SAS</title>

    <!-- Custom fonts for this template-->
    <link href='{% static "vendor/fontawesome-free/css/all.min.css"%} ' rel="stylesheet">
    
    
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    
    <link href="{%static "css/css/sb-admin-2.min.css"%}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
                <div class="sidebar-brand-icon rotate-n-0">
                    <i class="fas fa-user"></i>
                </div>
                <div class="sidebar-brand-text mx-3">
                    {% if usr_dl.user_role == '2'%}
                    <span>Teacher</span>
                    {% elif usr_dl.user_role == '3'%}
                    <span>Admin</span>
                    {% else %}
                    <span>Student</span>
                    {% endif %}
                </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    {% if usr_dl.user_role == '2'%}
                    <span>Dashboard</span>
                    {% elif usr_dl.user_role == '3'%}
                    <span>Dashboard</span>
                    {% else %}
                    <span>Dashboard</span>
                    {% endif %}</a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>
            {% if usr_dl.user_role == '2' %}
            
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'teacher:takeattendance' %}" data-toggle="" data-target=""
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Take Attendance</span>
                </a>

            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'teacher:showattendance' %}" data-toggle="" data-target=""
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>View Attendance</span>
                </a>

            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'teacher:showStudentByTeacher' %}" data-toggle="" data-target="#"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Add Student Course</span>
                </a>

            </li>

            {% elif usr_dl.user_role == '3' %}
            
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'subadmin:index' %}" data-toggle="" data-target="#"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Dashboard</span>
                </a>

            </li>
            
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'subadmin:showclass' %}" data-toggle="" data-target=""
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Add Classroom</span>
                </a>

            </li>

            {% else %}

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'student:index' %}" data-toggle="" data-target=""
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Dashboard</span>
                </a>

            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'student:addview' %}" data-toggle="" data-target=""
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>View Attendance</span>
                </a>

            </li>

            {% endif %}

            <!-- Nav Item - Utilities Collapse Menu -->
            

            <!-- Divider -->
            
            <!-- Nav Item - Pages Collapse Menu -->
            

           

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
          

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        

                       

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                                <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
               {% block body_block %}

               {% endblock %}

            </div>
            <!-- End of Main Content -->



            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; This is Muntasir</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            {% if usr_dl.user_role == '2' %}
            <form action="{% url 'teacher:logout' %}" method="POST">
            {% elif usr_dl.user_role == '3' %}
            <form action="{% url 'subadmin:logout' %}" method="POST">
            {% else %}
            <form action="{% url 'student:logout' %}" method="POST">
            {% endif %}
            
            {%csrf_token%}
                


            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="submit" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <input class="btn btn-primary" type="submit" value="Logout">
                </div>
            </div>
        </form>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
   
    <script src="{%static "vendor/jquery/jquery.min.js"%}"></script>

    <script src="{%static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{%static "vendor/jquery-easing/jquery.easing.min.js"%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{%static "JS/js/sb-admin-2.min.js"%}"></script>

    <!-- Page level plugins -->
    <script src="{%static "vendor/chart.js/Chart.min.js"%}"></script>

    <!-- Page level custom scripts -->
    <script src="{%static "JS/js/demo/chart-area-demo.js"%}"></script>
    <script src="{%static "JS/js/demo/chart-pie-demo.js"%}"></script>

    

</body>

</html>

smartApp/templates/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SAS</title>
    <link href="https://fonts.googleapis.com/css?family=Heebo:400,500,700|Playfair+Display:700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'landing/dist/css/style.css' %}">
    
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
</head>
<body class="is-boxed has-animations">
    <div class="body-wrap boxed-container">
        

        <main>
            <section class="hero">
                <div class="container">
                    <div class="hero-inner">
						<div class="hero-copy">
	                        <h1 class="hero-title mt-0">Please choose your login action</h1>
	                        <p class="hero-paragraph">If you are a teacher you get click in te Login Teacher. Otherwise you can Click Login student Button</p>
	                        <div class="hero-cta"><a class="button button-shadow" href="{% url 'student:login' %}">Login Student</a><a class="button button-primary button-shadow" href="{% url 'teacher:login' %}">Login Teacher</a></div>
						</div>
						
                    </div>
                </div>
            </section>

           

           

    <script src="{% static 'landing/dist/js/main.min.js'%}"></script>
</body>
</html>