smartApp/smartApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include 
from student import views
urlpatterns = [
    path('',views.landingPage,name = "landingPage"),
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('subadmin/',include('subadmin.urls')),
]

smartApp/student/urls.py
from django.contrib import admin
from django.urls import path
from student import views
app_name = 'student'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('addview/',views.addView, name = 'addview'),
    path('showattendance/',views.showAttendance, name = 'showattendance'),
    

    
]

smartApp/teacher/urls.py
from django.contrib import admin
from django.urls import path
from teacher import views
app_name = 'teacher'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('getstudentbyyear/<str:subject>',views.getStudentByYear,name = 'getstudentbyyear'),
    path('showStudentByTeacher',views.showStudentByTeacher ,name = 'showStudentByTeacher'),
    path('insertstdwicourse',views.insertStdWiCourse ,name = 'insertstdwicourse'),
    path('takeattendance/',views.takeAttendance,name = 'takeattendance'),
    path('addattendance/',views.addAttendance, name = 'addattendance'),
    path('attendance/',views.Attendance, name = 'attendance'),
    path('showattendance/',views.showAttendance,name = 'showattendance'),
    path('viewattendance/',views.viewAttendance,name = 'viewattendance')
    

    
]

smartApp/teacher/models.py
from django.db import models

import uuid
from django.contrib.auth.models import User


class Teacher(models.Model):
    #id = models.AutoField(primary_key = True)
    #id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length= 50)
    last_name = models.CharField(max_length= 50)
    phone_number = models.CharField(max_length= 50)
    dept = models.CharField(max_length= 50)
    faculty = models.CharField(max_length= 50)
    designation = models.CharField(max_length= 50,default = '')
    user_role = models.CharField(max_length=50,default='2')
   
    
    def __str__(self):
        
        return self.first_name

class Course(models.Model):
    student_code = models.CharField(max_length= 50)
    subject_code = models.CharField(max_length= 50)

    def __str__(self):
        return self.student_code +" "+self.subject_code


class AttendanceDB(models.Model):
    course_code = models.CharField(max_length= 50)
    student_id = models.CharField(max_length= 50)
    comment = models.CharField(max_length= 50)
    status = models.CharField(max_length= 50)
    at_date = models.DateField()

    def __str__(self):
        return self.course_code +" "+self.student_id

        

smartApp/teacher/views.py
from django.shortcuts import render
from teacher.models import Teacher, Course ,AttendanceDB
from django.http import HttpResponse ,HttpResponseRedirect
from django.contrib.auth.models import User
from subadmin.models import Class
from student.models import StudentList
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime
import cv2

@login_required
def index(request):
    usr_dl=Teacher.objects.filter(user=request.user).values()
    teacher_id = usr_dl[0]['id']
    course_details = Class.objects.filter(course_teacher = teacher_id).values()
    

    dict = {
        'usr_dl':usr_dl[0],
        'course':course_details,
    }
    return render(request,'teacher/dashboard.html',context = dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
      
        user = authenticate(username = username,password = password)
        if user:
            if user.is_active:
                login(request,user)
                
                dict = {
                    'user':user,
                    
                }
                return HttpResponseRedirect(reverse('teacher:index'))
                #return render(request,'student/dashboard.html',context = dict)

            else:
                return HttpResponse('Account is not active')
        else:
            return HttpResponse('Login unsuccesfull')
    else:
        return render(request,'teacher/auth/login.html')

def register(request):
    diction = {
        'success':'Registration Successfully'
    }
    if request.method == 'POST':
        obj=Teacher()
        user = User()
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        
        user.set_password(request.POST.get('password'))
        users = user.save()
        
        obj.user = user
        obj.first_name= request.POST.get('first_name')
        obj.last_name= request.POST.get('last_name')
        obj.mobile_number= request.POST.get('mobile_number')
        obj.dept = request.POST.get('department')
        obj.faculty = request.POST.get('faculty')
        obj.designation = request.POST.get('desigation')
        
        obj.save()
        return render(request,'teacher/auth/login.html',context = diction)
    else:
        
        return render(request,'teacher/auth/register.html',context = diction)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('teacher:login'))

def getStudentByYear(request,subject):
    course = Course.objects.filter(subject_code = subject).values()
    usr_dl=Teacher.objects.filter(user=request.user).values()
    lst = []
    for i in course:
        std = i['student_code']
        student = StudentList.objects.filter(id = std).values()
        lst.append(student[0])
    
    dict = {
        'usr_dl':usr_dl[0],
        'student':lst,
        
    }
    return render(request,'teacher/addstudent.html',context=dict)


def showStudentByTeacher(request):
    usr_dl=Teacher.objects.filter(user=request.user).values()
    if request.method == 'POST':
        year = request.POST.get('year')
        semister = request.POST.get('semister')
        dept = request.POST.get('department')
        subject = request.POST.get('subject')
        obj = StudentList.objects.filter(year = year,semister = semister,department = dept).values()
        

        dict = {
            'usr_dl':usr_dl[0],
            'student':obj,
            'subject':subject,
            'year':year,
            'semister':semister,
            'dept':dept,
        }

        
        return render(request,'teacher/student/showStudent.html',context=dict)

    else:
        teacher = Teacher.objects.filter(user=request.user).values()
        teacher_id = teacher[0]['id']
        subject = Class.objects.filter(course_teacher = teacher_id).values()
        
        dict = {
            'usr_dl':usr_dl[0],
            'teacher_id' : teacher[0]['id'],
            'subject':subject,
        }
        return render(request,'teacher/student/studentAddCourse.html',context=dict)


def insertStdWiCourse(request):
    std_code = request.POST.getlist('std_id')
    subject_code = request.POST.get('subject')
    for i in std_code:
        obj = Course()
        obj.student_code = i
        obj.subject_code = subject_code
        obj.save()
    
    return HttpResponseRedirect(reverse('teacher:showStudentByTeacher'))

def takeAttendance(request):
    usr_dl=Teacher.objects.filter(user=request.user).values()
    teacher = Teacher.objects.filter(user=request.user).values()
    teacher_id = teacher[0]['id']
    subject = Class.objects.filter(course_teacher = teacher_id).values()
    print(teacher_id)
    dict = {
        'usr_dl':usr_dl[0],
        'teacher_id' : teacher[0]['id'],
        'subject':subject,
    }
    return render(request,'teacher/attendance/takeAtten.html',context=dict)

def addAttendance(request):
    if request.method == 'POST':
        subject_code = request.POST.get('subject')
        subject_name = Class.objects.filter(course_code = subject_code).values()
        usr_dl=Teacher.objects.filter(user=request.user).values()
        course = Course.objects.filter(subject_code = subject_code).values()
        
        lst = []
        for i in course:
            std = i['student_code']
            student = StudentList.objects.filter(id = std).values()
            lst.append(student[0])

        
        dict = {
            'usr_dl':usr_dl[0],
            'course_name':subject_name[0]['course_name'],
            'course_code':subject_code,
            'student':lst
            
        }
        return render(request,'teacher/attendance/addAtten.html',context=dict)
    else:
        pass


    


def Attendance(request):
    
    if request.method == 'POST':
        course_code = request.POST.get('course_code')
        student_id = request.POST.getlist('student_id')
        course_name = request.POST.get('course_name')
        comment = request.POST.getlist('comment')
        first_name = request.POST.getlist('first_name')
        last_name = request.POST.getlist('last_name')

        if 'auto' in request.POST:
            cap = cv2.VideoCapture(0)
            while(True):
                ret, frame = cap.read()
        #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

                cv2.imshow('frame',frame)
                if cv2.waitKey(20) & 0xFF == ord('q'):
                    break
        
        

            cap.release()
            cv2.destroyAllWindows()
            return render(request,'teacher/attendance/addAtten.html')

        else:
            
        
            print(course_code)
        
            rang  = range(len(student_id))
            for i in rang:
                x = datetime.datetime.now()
                d = datetime.date(x.year,x.month,x.day)

            
                atn = AttendanceDB()
                atn.course_code = course_code
                atn.student_id = student_id[i]
                atn.comment = comment[i]
                atn.status = request.POST.get(student_id[i])
                atn.at_date = d
                atn.save()
            return render(request,'teacher/attendance/addAtten.html')


        

    else:
        pass

def showAttendance(request):
    usr_dl=Teacher.objects.filter(user=request.user).values()
    teacher_id = usr_dl[0]['id']
    
    details = Class.objects.filter(course_teacher = teacher_id).values()
    print(details)
    dict={
        'usr_dl':usr_dl[0],
        'course':details,
        'teacher_id':teacher_id,
    }
    return render(request,'teacher/attendance/create.html',context = dict)


def viewAttendance(request):
    usr_dl=Teacher.objects.filter(user=request.user).values()
    if request.method == 'POST':
        course_code = request.POST.get('course_code')
        res = AttendanceDB.objects.filter(course_code = course_code).values()
        print(res)
        dict = {
            'usr_dl':usr_dl[0],
            'details':res
        }
        return render(request,'teacher/attendance/show.html',context = dict)

    


    

smartApp/templates/teacher/attendance/addAtten.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
</head>

<body class="" style="background: #edf2f7;">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet"
        href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">

    <form action="{% url 'teacher:attendance' %}" method="POST">
        {% csrf_token %}
        <section class=" py-1 bg-blueGray-50">
            <div class="w-full lg:w-10/12 px-4 mx-auto mt-6">
                <div
                    class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0">

                    <div class="rounded-t bg-white mb-0 px-6 py-6">
                        <div class="text-center flex justify-between">
                            <h6 class="text-blueGray-700 text-xl font-bold">
                                Student Details
                            </h6>

                            <a href=""><button
                                    class="bg-pink-500 text-white active:bg-pink-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 ease-linear transition-all duration-150"
                                    type="submit" name="auto">
                                    Open Camera For Attendance
                                </button><button
                                    class="bg-pink-500 text-white active:bg-pink-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 ease-linear transition-all duration-150"
                                    type="submit" name="mannual">
                                    Add on Course
                                </button></a>
                        </div>
                    </div>

                    <div class="flex flex-wrap" style="padding-top: 20px;">
                        <div class="w-full lg:w-6/12 px-4">
                            <div class="relative w-full mb-3">
                                <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                    htmlfor="grid-password">
                                    Course Code
                                </label>
                                <input type="text"
                                    class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                    value="{{course_code}}" name="" disabled>
                                    <input type="hidden" name="course_code" value="{{course_code}}">
                            </div>
                        </div>

                        <div class="w-full lg:w-6/12 px-4">
                            <div class="relative w-full mb-3">
                                <label class="block uppercase text-blueGray-600 text-xs font-bold mb-2"
                                    htmlfor="grid-password">
                                    Course Name
                                </label>
                                <input type="text"
                                    class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"
                                    value="{{course_name}}" name="course_name" disabled>
                                
                            </div>
                        </div>



                    </div>
                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">

                            <thead
                                class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                <tr>
                                    <th scope="col" class="px-6 py-3">
                                        Student ID
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Name
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Action( P - L - A)
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Comment
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for obj in student %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <th scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        {{obj.student_id}}
                                        <input type="hidden" name="student_id" value="{{obj.student_id}}">
                                    </th>
                                    <td class="px-6 py-4">
                                        {{obj.first_name}} {{obj.last_name}}
                                        <input type="hidden" name="first_name" value="{{obj.first_name}}">
                                        <input type="hidden" name="last_name" value="{{obj.last_name}}">
                                    </td>
                                    <td class="px-6 py-4">
                                        <div style="padding-left:20px;" class="" role="group" aria-label="Basic radio toggle button group">
                                            <input type="radio" value="P" class="btn-check" name="{{obj.student_id}}" id="btnradio1" autocomplete="off" checked>
                                            <input type="radio" value="L" class="btn-check" name="{{obj.student_id}}" id="btnradio2" autocomplete="off">
                                            <input type="radio" value="A" class="btn-check" name="{{obj.student_id}}" id="btnradio3" autocomplete="off">
                                            
                                          </div>
                                          
                                    </td>
                                    <td class="px-6 py-4">

                                        <input type="Text" name="comment" value="" placeholder="Add Comment Here">
                                    </td>


                                    {% endfor %}
                                </tr>

                            </tbody>
                        </table>
                    </div>


                </div>

            </div>
        </section>
    </form>
</body>
{% endblock%}ß

smartApp/templates/teacher/attendance/create.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<button type="button" id="btn1" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Show</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Select Course</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'teacher:viewattendance' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{teacher_id}}" name="student_id">
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Course:</label>
                        <select type="text" class="form-control form-control-user" id="exampleInputPassword"
                            name="course_code">

                            <option required>Select Course</option>
                            {% for obj in course %}
                            <option value="{{obj.course_code}}">{{obj.course_name}}</option>   
                            {% endfor %}               
                        </select>
                    </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Show</button>
            </div>
            </form>
        </div>
    </div>
</div>

<script>

</script>
{% endblock%}

smartApp/templates/teacher/attendance/show.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
</head>

<body class="" style="background: #edf2f7;">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet"
        href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">

        <form action=" " method="POST">
            
    <section class=" py-1 bg-blueGray-50">
        <div class="w-full lg:w-10/12 px-4 mx-auto mt-6">
            <div
                class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0">

                    <div class="rounded-t bg-white mb-0 px-6 py-6">
                        <div class="text-center flex justify-between">
                            <h6 class="text-blueGray-700 text-xl font-bold">
                                Attendance Details
                            </h6>
                            
                        </div>
                    </div>

                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                            
                            <thead
                                class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                <tr>
                                    <th scope="col" class="px-6 py-3">
                                        Course Code
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Student Id
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Status
                                    </th>

                                    <th scope="col" class="px-6 py-3">
                                        Date
                                    </th>

                                    <th scope="col" class="px-6 py-3">
                                        Comment
                                    </th>

                                    
                                </tr>
                            </thead>
                            <tbody>
                            {% for obj in details %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <th scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        {{obj.course_code}}
                                    </th>
                                    <td class="px-6 py-4">
                                        {{obj.student_id}}
                                    </td>
                                    <td class="px-6 py-4">
                                        {% if obj.status == 'L' %}
                                        <span style="color:cyan;">Let</span>
                                        {% elif obj.status == 'A' %}
                                        <span  style="color:red;">Absent</span>
                                        {% else %}
                                        <span style="color:greenyellow;">Present</span>
                                        {% endif %}
                                        

                                    </td>
                                    <td class="px-6 py-4">
                                        {{obj.at_date}}
                                    </td>
                                    <td class="px-6 py-4">
                                        {{obj.comment}}
                                    </td>
                                   
                                   
                                {% endfor %}
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>


            </div>

        </div>
    </section>
</form>
</body>
{% endblock%}ß

smartApp/templates/teacher/attendance/takeAtten.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<button type="button" id="btn1" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Show</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Select Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'teacher:addattendance' %}" method="POST">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Subject:</label>
                        <select type="text" class="form-control form-control-user" id="exampleInputPassword"
                            name="subject">

                            <option required>Select Subject</option>
                            {% for obj in subject %}
                            <option value="{{obj.course_code}}">{{obj.course_name}}</option>   
                            {% endfor %}               
                        </select>
                    </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Send message</button>
            </div>
            </form>
        </div>
    </div>
</div>

<script>

</script>
{% endblock%}