smartApp/smartApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include 
from student import views
urlpatterns = [
    path('',views.landingPage,name = "landingPage"),
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('subadmin/',include('subadmin.urls')),
]

smartApp/student/urls.py
from django.contrib import admin
from django.urls import path
from student import views
app_name = 'student'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('addview/',views.addView, name = 'addview'),
    path('showattendance/',views.showAttendance, name = 'showattendance'),
    

    
]

smartApp/teacher/urls.py
from django.contrib import admin
from django.urls import path
from teacher import views
app_name = 'teacher'
urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('register/',views.register, name = 'register'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('getstudentbyyear/<str:subject>',views.getStudentByYear,name = 'getstudentbyyear'),
    path('showStudentByTeacher',views.showStudentByTeacher ,name = 'showStudentByTeacher'),
    path('insertstdwicourse',views.insertStdWiCourse ,name = 'insertstdwicourse'),
    path('takeattendance/',views.takeAttendance,name = 'takeattendance'),
    path('addattendance/',views.addAttendance, name = 'addattendance'),
    path('attendance/',views.Attendance, name = 'attendance'),
    path('showattendance/',views.showAttendance,name = 'showattendance'),
    path('viewattendance/',views.viewAttendance,name = 'viewattendance')
    

    
]

smartApp/student/models.py
from django.db import models

from django.contrib.auth.models import User


class StudentList(models.Model):
    #id = models.AutoField(primary_key = True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length= 50)
    first_name = models.CharField(max_length= 50)
    last_name = models.CharField(max_length= 50)
    department = models.CharField(max_length=50,default='')
    year = models.CharField(max_length= 50)
    semister = models.CharField(max_length= 50,default = '')
    section = models.CharField(max_length= 50,default = '')
    user_role = models.CharField(max_length=50,default='1')
   

    def __str__(self):
        return self.first_name

        

smartApp/student/views.py
from django.shortcuts import render
from django.http import HttpResponse ,HttpResponseRedirect
from student.models import StudentList
from teacher.models import Course,AttendanceDB
from subadmin.models import Class
from django.contrib.auth.models import User

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
def landingPage(request):
    return render(request,'landing.html')


    
@login_required
def index(request):
    usr_dl=StudentList.objects.filter(user=request.user).values()
    course = Course.objects.filter(student_code = usr_dl[0]['id']).values()
    
    
    lst = []
    for i in course:
        std = i['subject_code']
        
        clas = Class.objects.filter(course_code = std).values()
        print(clas)
        lst.append(clas[0])


    student_list = StudentList.objects.filter()
    diction = {
        'text':'i am a text from akash',
        'name':'akash',
        'course':lst,
    
    }
    return render(request,'student/dashboard.html',context = diction)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        print(password)
        user = authenticate(username = username,password = password)
        print(user)
        if user:
            if user.is_active:
                login(request,user)
                dict = {
                    'user':user
                }
                return HttpResponseRedirect(reverse('student:index'))
                #return render(request,'student/dashboard.html',context = dict)

            else:
                return HttpResponse('Account is not active')
        else:
            return HttpResponse('Login unsuccesfull')
    else:
        return render(request,'student/auth/login.html')



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('student:login'))

def register(request):
    diction = {}
    if request.method == 'POST':
        student=StudentList()
        user = User()
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        
        user.set_password(request.POST.get('password'))
        users = user.save()
        
        student.user = user
        student.student_id= request.POST.get('student_id')
        student.first_name= request.POST.get('first_name')
        student.last_name= request.POST.get('last_name')
        student.year= request.POST.get('year')
        student.semister = request.POST.get('semister')
        student.section = request.POST.get('section')
        
        student.save()
        return render(request,'student/auth/login.html',context = diction)
    else:
        
        return render(request,'student/auth/register.html',context = diction)


def addView(request):
    usr_dl=StudentList.objects.filter(user=request.user).values()
    course = Course.objects.filter(student_code = usr_dl[0]['id']).values()
    print(usr_dl[0]['student_id'])
    print(course)

    dict = {
        'usr_dl':usr_dl[0],
        'course':course,
        'student_id':usr_dl[0]['student_id'],
    }
    return render(request,'student/view/create.html',context = dict)

def showAttendance(request):
    if request.method == 'POST':
        std = request.POST.get('student_id')
        course_code = request.POST.get('course_code')
        res = AttendanceDB.objects.filter(course_code = course_code,student_id=std).values()
        dict = {
            'details':res
        }
        return render(request,'student/view/show.html',context = dict)


    

smartApp/templates/student/view/create.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<button type="button" id="btn1" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Show</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Select Course</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'student:showattendance' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{student_id}}" name="student_id">
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Course:</label>
                        <select type="text" class="form-control form-control-user" id="exampleInputPassword"
                            name="course_code">

                            <option required>Select Course</option>
                            {% for obj in course %}
                            <option value="{{obj.subject_code}}">{{obj.subject_code}}</option>   
                            {% endfor %}               
                        </select>
                    </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Show</button>
            </div>
            </form>
        </div>
    </div>
</div>

<script>

</script>
{% endblock%}

smartApp/templates/student/view/show.html
<!DOCTYPE html>
{% extends "index.html"%}
{% block body_block %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
</head>

<body class="" style="background: #edf2f7;">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet"
        href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">

        <form action="{% url 'teacher:insertstdwicourse' %}" method="POST">
            {% csrf_token %}
    <section class=" py-1 bg-blueGray-50">
        <div class="w-full lg:w-10/12 px-4 mx-auto mt-6">
            <div
                class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0">

                    <div class="rounded-t bg-white mb-0 px-6 py-6">
                        <div class="text-center flex justify-between">
                            <h6 class="text-blueGray-700 text-xl font-bold">
                                Attendance Details
                            </h6>
                            
                        </div>
                    </div>

                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                            
                            <thead
                                class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                <tr>
                                    <th scope="col" class="px-6 py-3">
                                        Course Code
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Student Id
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Status
                                    </th>

                                    <th scope="col" class="px-6 py-3">
                                        Date
                                    </th>

                                    <th scope="col" class="px-6 py-3">
                                        Comment
                                    </th>

                                    
                                </tr>
                            </thead>
                            <tbody>
                            {% for obj in details %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <th scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        {{obj.course_code}}
                                    </th>
                                    <td class="px-6 py-4">
                                        {{obj.student_id}}
                                    </td>
                                    <td class="px-6 py-4">
                                        {% if obj.status == 'L' %}
                                        <span style="color:cyan;">Let</span>
                                        {% elif obj.status == 'A' %}
                                        <span  style="color:red;">Absent</span>
                                        {% else %}
                                        <span style="color:greenyellow;">Present</span>
                                        {% endif %}
                                        

                                    </td>
                                    <td class="px-6 py-4">
                                        {{obj.at_date}}
                                    </td>
                                    <td class="px-6 py-4">
                                        {{obj.comment}}
                                    </td>
                                   
                                   
                                {% endfor %}
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>


            </div>

        </div>
    </section>
</form>
</body>
{% endblock%}ß